services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: casheer-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pipinstallpython--upgrade
      POSTGRES_DB: casheer_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: casheer-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Auth Service
  auth-service:
    image: auth-service
    container_name: casheer-auth
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
    - ./casheer-auth-service/.env
    depends_on:
      postgres:
        condition: service_healthy

  # Menu Service
  menu-service:
    image: menu-service
    container_name: casheer-menu
    restart: unless-stopped
    ports:
      - "3002:3002"
    env_file:
    - ./casheer-menu-service/.env
    depends_on:
      postgres:
        condition: service_healthy

  # Report Service
  report-service:
    image: report-service
    container_name: casheer-report
    restart: unless-stopped
    ports:
      - "3003:3003"
    env_file:
        - ./casheer-report-service/.env
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  postgres_data:  